### ISSUE TITLE
Address no longer supports symbolic links

### ISSUE THREAD

**Issue by sargonphin** [mcm1957/ioBroker.snmp#16]
**Describe the bug**
Since update >2.0, the adapter no longer supports usage of symbolic link as a device address. Raises the error "invalid format"

**To Reproduce**
- Open adapter settings
- Add a new device
- Input a symbolic link in "IP address" field
- Save and reload

**Expected behavior**  
The adapter sends a DNS request to local DNS server to lookup the local device and connects to the device with its IP

**Versions:**
 - Adapter version: 2.1.7
 - JS-Controller version: 4.0.23
 - Node version: 16.13.2
 - Operating system: RaspberryOS (Debian 11)

**Additional context**
Using a symolic link used to work properly in the address field. I suppose there have been syntax checks added which dissalow the usage of non-standard IPv4(6) addresses

**Comment by sargonphin** [comment]
![image](https://user-images.githubusercontent.com/85966195/188311523-d2665e24-3272-40b2-a9b5-3377e5278aec.png)
![image](https://user-images.githubusercontent.com/85966195/188311528-bb680cc4-3b79-4cde-9ae3-bee79d4314d5.png)

**Comment by mcm1957** [comment]
moved to https://github.com/iobroker-community-adapters/ioBroker.snmp/issues/165
